spring:
  datasource:
    url: jdbc:mysql://localhost:3306/b2bmall?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 192.168.10.100
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200
server:
  port: 8080

mybatis:
  type-aliases-package: com.legensity.b2bmall.*.entity
  mapper-locations: classpath*:com/legensity/b2bmall/*/dao/*.xml
  global-config:
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#短信
message:
  serviceURL: app.cloopen.com
  serviceToken: f268f797901442f29beeee7d32424b7a
  serviceSID: 8aaf070856d4826c0156d93c8ff505cd
  serviceAppID: 8aaf07086e0115bb016e7ca6f95144a9
  smsVerifyCodeTemplate: 486069


