spring:
  datasource:
    url: jdbc:mysql://localhost:3306/b2bmall?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  #当出现相同名字的类进行注册时，准许覆盖注册
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8080

mybatis:
  type-aliases-package: com.legensity.b2bmall.*.entity
  mapper-locations: classpath*:com/legensity/b2bmall/*/dao/*.xml
  global-config:
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#短信
message:
  serviceURL: app.cloopen.com
  serviceToken: f268f797901442f29beeee7d32424b7a
  serviceSID: 8aaf070856d4826c0156d93c8ff505cd
  serviceAppID: 8aaf07086e0115bb016e7ca6f95144a9
  smsVerifyCodeTemplate: 486069


